name: nodejs eks feature
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
jobs:
  build_nodejs:
   runs-on: ubuntu-latest
   steps:
     - name: calling version
       run: |
         echo "Reading version"

     - name: reading inputs
       run: |
         echo "project  ${{ inputs.project }}"
         echo "component  ${{ inputs.component }}"